env:
    browser: true
    es2021: true
    node: true
    jest: true
    serviceworker: true
ignorePatterns:
    - "build"
    - ".*.js"
    - "*.config.js"
    - "node_modules"
extends:
    - standard
    - plugin:import/typescript
    - plugin:jest/recommended
    - prettier
    - prettier/@typescript-eslint
    - prettier/react
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: 12
    sourceType: module
plugins:
    - "@typescript-eslint"
    - jest
rules:
    "no-unused-vars": 0
    "@typescript-eslint/no-unused-vars": 2
    "camelcase": 0
    "no-useless-constructor": 0
